services:
  securepastebox:
    image: ${DOCKER_REGISTRY-}securepastebox
    build:
      context: .
      dockerfile: SecurePasteBox/Dockerfile
    ports:
      - 9955:8080 
    environment:
      - KEY_STORAGE_TYPE=Files
    volumes:
      - spb-data:/data
    networks:
      - spb-network

volumes:
  spb-data:

networks:
  spb-network:
    name: securepastebox  